# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tv_video_app_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tv_video_app_test
    pod 'TVVLCKit', '3.3.0'
  target 'tv_video_app_testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tv_video_app_testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
